// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxR7beQR_lAAkh1d0UWWDSxpkWMKAvf4',
    appId: '1:644213519424:web:8a3c1a108ae58a08e89ba5',
    messagingSenderId: '644213519424',
    projectId: 'stifar-75137',
    authDomain: 'stifar-75137.firebaseapp.com',
    storageBucket: 'stifar-75137.appspot.com',
    measurementId: 'G-J79D7TEZ4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2MCCcf1PymEYCO1ZJUfyCR6EoH4t12_0',
    appId: '1:644213519424:android:f8a0340c0c5f01fce89ba5',
    messagingSenderId: '644213519424',
    projectId: 'stifar-75137',
    storageBucket: 'stifar-75137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJBIlzGm_u3qOsybfllq6K4lBoqWPdUGI',
    appId: '1:644213519424:ios:a708f45946565946e89ba5',
    messagingSenderId: '644213519424',
    projectId: 'stifar-75137',
    storageBucket: 'stifar-75137.appspot.com',
    iosBundleId: 'com.atomtekno.hahai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJBIlzGm_u3qOsybfllq6K4lBoqWPdUGI',
    appId: '1:644213519424:ios:a708f45946565946e89ba5',
    messagingSenderId: '644213519424',
    projectId: 'stifar-75137',
    storageBucket: 'stifar-75137.appspot.com',
    iosBundleId: 'com.atomtekno.hahai',
  );
}
